---
- name: simple block usage
  hosts: all
  tasks:
  - name: setting up httpd
    block:
    - name:
      yum:
        name: httpd
        state: present
    - name: restart httpd
      service: 
        name: httpd
        state: started
    when: ansible_distribution == "CentOS"