---
- name: configuring SSH 
  hosts: servers
  tasks:
  - name: Disable root SSH login
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: "^PermitRootLogin"
      line: "PermitRootLogin no"
    notify: restart ssh 

  handlers:
  - name: restart ssh
    service: 
      name: sshd 
      state: restarted