---
- name: create usesrs with encriopted password
  hosts: rhce3
  vars_prompt:
    - name: passwd
      prompt: informe uma senha
  vars:
    user: sharon
  tasks:
    - debug:
        msg: "{{ '{{ passwd }}'| password_hash('sha512','myrandomsalt') }}"
      register: mypass
    - debug:
        var: mypass
    - name: create a user
      user:
        name: "{{ user }}"
        password: "{{ mypass.msg }}"