---
- name: exercice 143
  hosts: rhce2
  tasks:
  - name: add a line to file before rebooting 
    lineinfile:
      create: true
      state: present
      path: /tmp/rebooted
      insertafter: EOF
      line: rebooted at {{ ansible_facts.date_time.time }}:{{ ansible_facts.date_time.second }}
  - name: run a cron job on a reboot
    cron: 
      name: "run on reboot"
      state: present
      special_time: reboot 
      job: "echo rebooted at $(date) >> /tmp/rebooted"
  - name: reboot managed hosts 
    reboot: 
      msg: reboot initialized by ansible 
      test_command: whoami
  - name: show reboot success
    debug: 
      msg: just rebooted successfully