---
- name: Certify there is no HTTPD or MYSQlD installed
  hosts: rhce1
  pre_tasks:
  - name: verify HTTPD
    yum: 
      name: httpd 
      state: absent
  - name: verify MYSQL 
    yum: 
      name: httpd
      state: absent

- name: Install NGINX and postgresql
  hosts: rhce1
  roles:
  - VeselaHouba.nginx
  - linux-system-roles.postgresql
