---
- name: create storage 
  hosts: rhce2
  tasks: 
  - name: create a new partition
    parted:
      name: files
      label: gpt
      device: /dev/sdb
      number: 1
      state: present
      part_start: 1MiB
      part_end: 2GiB
  - name: create another new partition
    parted: 
      name: swap
      label: gpt
      device: /dev/sdb
      number: 2
      state: present
      part_start: 2GiB
      part_end: 4GiB
      flags: [ lvm ]
  - name: create a volume group
    lvg:
      vg: vgdata
      pvs: /dev/sdb1
  - name: create a logical volume 
    lvol:
      lv: lvdata
      size: 100%FREE
      vg: vgdata
  - name: create an xfs filesystem 
    filesystem:
      dev: /dev/vgdata/lvdata
      fstype: xfs
  - name: mount filesystem
    mount:
      src: /dev/vgdata/lvdata
      fstype: xfs
      state: mounted
      path: /mydir
      
