---
- name: using packages facts
  hosts: rhce1
  vars:
    my_package: nmap
  tasks:
  - name: install package
    yum: 
      name: "{{ my_package }}"
      state: present
  - name: update páckage facts
    package_facts:
      manager: auto
  - name: show package facts for {{ my_package }}
    debug:
      var: ansible_facts.packages[my_package]
    when: my_package in ansible_facts.packages