---
- name: restart sshd service if httpd is running
  hosts: all
  tasks: 
  - name: get httpd serice status
    command: systemctl is-active httpd
    ignore_errors: yes
    register: result
  - name: show the result variable contents
    debug:
      msg: printing contents of the registered variable {{ result }}
  - name: restart sshd service
    service:
      name: sshd
      state: restarted
    when: result.rc == 0