---
- name: conditionals tests
  hosts: all
  tasks:
  - name: update the kernel if suficient space is available on /boot
    package: 
      name: kernel 
      state: latest
    loop: "{{ ansible_facts.mounts }}"
    when: item.mount == "/boot" and item.size_available > 20000000