---
- name: configure web services
  hosts: webservers
  tasks:
  - name: this is the {{ web_package }} package
    debug:
      msg: "installing {{ web_package }}"
  - name: this is the {{ web_package }} service
    debug:
      msg: "Starting the {{ web_package }} service"
